import { Button } from '@/components/ui/button'

import { useAppStore } from '@/stores'

const featureCards = [
  {
    description:
      'Route files now live under src/pages and are generated by vite-plugin-pages.',
    icon: 'i-solar-widget-4-outline',
    title: 'Conventional pages',
  },
  {
    description:
      'Custom route registration and guard logic live under src/routers for anything not covered by the filesystem.',
    icon: 'i-solar-route-outline',
    title: 'Custom routers',
  },
  {
    description:
      'UI components and helper methods now live directly inside src/components, src/libs, and src/styles.',
    icon: 'i-solar-layers-outline',
    title: 'Local app structure',
  },
  {
    description:
      'Auto imports cover React hooks, react-router-dom, react-use, and your own composables via src/typings/auto-imports.d.ts.',
    icon: 'i-solar-code-outline',
    title: 'Generated typings',
  },
]

export default function HomePage() {
  const appName = useAppStore((state) => state.appName)
  const demoCount = useAppStore((state) => state.demoCount)
  const incrementDemoCount = useAppStore((state) => state.incrementDemoCount)
  const resetDemoCount = useAppStore((state) => state.resetDemoCount)

  return (
    <section className="space-y-8">
      <div className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]">
        <div className="space-y-5">
          <div className="border-border/70 bg-muted/40 text-muted-foreground inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-medium">
            <span className="i-carbon-logo-react inline-block size-4" />
            {appName}
          </div>
          <div className="max-w-3xl space-y-3">
            <h2 className="text-4xl font-semibold tracking-tight text-balance sm:text-5xl">
              Your React starter now follows your preferred single-app
              directory habits.
            </h2>
            <p className="text-muted-foreground max-w-2xl text-sm leading-7 sm:text-base">
              `typings`, `styles`, `stores`, `setups`, `services`, `routers`,
              `libs`, `layouts`, `pages`, `composables`, and `components` are
              all wired into the actual runtime instead of being empty folders.
            </p>
          </div>
          <div className="flex flex-wrap gap-3">
            <Button onClick={incrementDemoCount}>
              <span className="i-solar-add-circle-outline inline-block size-4" />
              Increase counter
            </Button>
            <Button onClick={resetDemoCount} variant="outline">
              <span className="i-solar-refresh-outline inline-block size-4" />
              Reset
            </Button>
          </div>
        </div>

        <div className="border-border/70 bg-muted/35 rounded-[1.75rem] border p-5">
          <div className="bg-background/90 space-y-3 rounded-[1.5rem] p-5 shadow-sm">
            <div className="text-muted-foreground text-xs font-medium tracking-[0.22em] uppercase">
              Zustand module
            </div>
            <div className="flex items-end justify-between gap-4">
              <div>
                <div className="text-5xl font-semibold tracking-tight">
                  {demoCount}
                </div>
                <p className="text-muted-foreground mt-2 text-sm">
                  This comes from <code>src/stores/modules/app</code>.
                </p>
              </div>
              <span className="i-solar-chart-outline text-muted-foreground inline-block size-12" />
            </div>
          </div>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {featureCards.map((card) => (
          <article
            key={card.title}
            className="border-border/70 bg-background/80 rounded-[1.5rem] border p-5 shadow-sm"
          >
            <div className="flex h-full flex-col gap-4">
              <span className={`${card.icon} inline-block size-7`} />
              <div className="space-y-2">
                <h3 className="text-lg font-semibold">{card.title}</h3>
                <p className="text-muted-foreground text-sm leading-6">
                  {card.description}
                </p>
              </div>
            </div>
          </article>
        ))}
      </div>
    </section>
  )
}
