/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as ImmersiveRouteRouteImport } from './pages/_immersive/route'
import { Route as AppRouteRouteImport } from './pages/_app/route'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as ImmersiveFullscreenRouteImport } from './pages/_immersive/fullscreen'
import { Route as AppUnauthorizedRouteImport } from './pages/_app/unauthorized'
import { Route as AppLoginRouteImport } from './pages/_app/login'
import { Route as AppCustomRouteRouteImport } from './pages/_app/custom-route'
import { Route as AppAboutRouteImport } from './pages/_app/about'
import { Route as AppAuthedRouteRouteImport } from './pages/_app/_authed/route'
import { Route as AppAuthedDashboardRouteImport } from './pages/_app/_authed/dashboard'
import { Route as AppAuthedAdminRouteRouteImport } from './pages/_app/_authed/_admin/route'
import { Route as AppAuthedAdminAdminRouteRouteImport } from './pages/_app/_authed/_admin/admin/route'
import { Route as AppAuthedAdminAdminUsersRouteImport } from './pages/_app/_authed/_admin/admin/users'

const ImmersiveRouteRoute = ImmersiveRouteRouteImport.update({
  id: '/_immersive',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ImmersiveFullscreenRoute = ImmersiveFullscreenRouteImport.update({
  id: '/fullscreen',
  path: '/fullscreen',
  getParentRoute: () => ImmersiveRouteRoute,
} as any)
const AppUnauthorizedRoute = AppUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomRouteRoute = AppCustomRouteRouteImport.update({
  id: '/custom-route',
  path: '/custom-route',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthedRouteRoute = AppAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthedDashboardRoute = AppAuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedAdminRouteRoute = AppAuthedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedAdminAdminRouteRoute =
  AppAuthedAdminAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AppAuthedAdminRouteRoute,
  } as any)
const AppAuthedAdminAdminUsersRoute =
  AppAuthedAdminAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AppAuthedAdminAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutRoute
  '/custom-route': typeof AppCustomRouteRoute
  '/login': typeof AppLoginRoute
  '/unauthorized': typeof AppUnauthorizedRoute
  '/fullscreen': typeof ImmersiveFullscreenRoute
  '/dashboard': typeof AppAuthedDashboardRoute
  '/admin': typeof AppAuthedAdminAdminRouteRouteWithChildren
  '/admin/users': typeof AppAuthedAdminAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutRoute
  '/custom-route': typeof AppCustomRouteRoute
  '/login': typeof AppLoginRoute
  '/unauthorized': typeof AppUnauthorizedRoute
  '/fullscreen': typeof ImmersiveFullscreenRoute
  '/dashboard': typeof AppAuthedDashboardRoute
  '/admin': typeof AppAuthedAdminAdminRouteRouteWithChildren
  '/admin/users': typeof AppAuthedAdminAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_immersive': typeof ImmersiveRouteRouteWithChildren
  '/_app/_authed': typeof AppAuthedRouteRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/custom-route': typeof AppCustomRouteRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/unauthorized': typeof AppUnauthorizedRoute
  '/_immersive/fullscreen': typeof ImmersiveFullscreenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_authed/_admin': typeof AppAuthedAdminRouteRouteWithChildren
  '/_app/_authed/dashboard': typeof AppAuthedDashboardRoute
  '/_app/_authed/_admin/admin': typeof AppAuthedAdminAdminRouteRouteWithChildren
  '/_app/_authed/_admin/admin/users': typeof AppAuthedAdminAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/custom-route'
    | '/login'
    | '/unauthorized'
    | '/fullscreen'
    | '/dashboard'
    | '/admin'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/custom-route'
    | '/login'
    | '/unauthorized'
    | '/fullscreen'
    | '/dashboard'
    | '/admin'
    | '/admin/users'
  id:
    | '__root__'
    | '/_app'
    | '/_immersive'
    | '/_app/_authed'
    | '/_app/about'
    | '/_app/custom-route'
    | '/_app/login'
    | '/_app/unauthorized'
    | '/_immersive/fullscreen'
    | '/_app/'
    | '/_app/_authed/_admin'
    | '/_app/_authed/dashboard'
    | '/_app/_authed/_admin/admin'
    | '/_app/_authed/_admin/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ImmersiveRouteRoute: typeof ImmersiveRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_immersive': {
      id: '/_immersive'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ImmersiveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_immersive/fullscreen': {
      id: '/_immersive/fullscreen'
      path: '/fullscreen'
      fullPath: '/fullscreen'
      preLoaderRoute: typeof ImmersiveFullscreenRouteImport
      parentRoute: typeof ImmersiveRouteRoute
    }
    '/_app/unauthorized': {
      id: '/_app/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AppUnauthorizedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/custom-route': {
      id: '/_app/custom-route'
      path: '/custom-route'
      fullPath: '/custom-route'
      preLoaderRoute: typeof AppCustomRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_authed': {
      id: '/_app/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_authed/dashboard': {
      id: '/_app/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthedDashboardRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/_app/_authed/_admin': {
      id: '/_app/_authed/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthedAdminRouteRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/_app/_authed/_admin/admin': {
      id: '/_app/_authed/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAuthedAdminAdminRouteRouteImport
      parentRoute: typeof AppAuthedAdminRouteRoute
    }
    '/_app/_authed/_admin/admin/users': {
      id: '/_app/_authed/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAuthedAdminAdminUsersRouteImport
      parentRoute: typeof AppAuthedAdminAdminRouteRoute
    }
  }
}

interface AppAuthedAdminAdminRouteRouteChildren {
  AppAuthedAdminAdminUsersRoute: typeof AppAuthedAdminAdminUsersRoute
}

const AppAuthedAdminAdminRouteRouteChildren: AppAuthedAdminAdminRouteRouteChildren =
  {
    AppAuthedAdminAdminUsersRoute: AppAuthedAdminAdminUsersRoute,
  }

const AppAuthedAdminAdminRouteRouteWithChildren =
  AppAuthedAdminAdminRouteRoute._addFileChildren(
    AppAuthedAdminAdminRouteRouteChildren,
  )

interface AppAuthedAdminRouteRouteChildren {
  AppAuthedAdminAdminRouteRoute: typeof AppAuthedAdminAdminRouteRouteWithChildren
}

const AppAuthedAdminRouteRouteChildren: AppAuthedAdminRouteRouteChildren = {
  AppAuthedAdminAdminRouteRoute: AppAuthedAdminAdminRouteRouteWithChildren,
}

const AppAuthedAdminRouteRouteWithChildren =
  AppAuthedAdminRouteRoute._addFileChildren(AppAuthedAdminRouteRouteChildren)

interface AppAuthedRouteRouteChildren {
  AppAuthedAdminRouteRoute: typeof AppAuthedAdminRouteRouteWithChildren
  AppAuthedDashboardRoute: typeof AppAuthedDashboardRoute
}

const AppAuthedRouteRouteChildren: AppAuthedRouteRouteChildren = {
  AppAuthedAdminRouteRoute: AppAuthedAdminRouteRouteWithChildren,
  AppAuthedDashboardRoute: AppAuthedDashboardRoute,
}

const AppAuthedRouteRouteWithChildren = AppAuthedRouteRoute._addFileChildren(
  AppAuthedRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAuthedRouteRoute: typeof AppAuthedRouteRouteWithChildren
  AppAboutRoute: typeof AppAboutRoute
  AppCustomRouteRoute: typeof AppCustomRouteRoute
  AppLoginRoute: typeof AppLoginRoute
  AppUnauthorizedRoute: typeof AppUnauthorizedRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthedRouteRoute: AppAuthedRouteRouteWithChildren,
  AppAboutRoute: AppAboutRoute,
  AppCustomRouteRoute: AppCustomRouteRoute,
  AppLoginRoute: AppLoginRoute,
  AppUnauthorizedRoute: AppUnauthorizedRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ImmersiveRouteRouteChildren {
  ImmersiveFullscreenRoute: typeof ImmersiveFullscreenRoute
}

const ImmersiveRouteRouteChildren: ImmersiveRouteRouteChildren = {
  ImmersiveFullscreenRoute: ImmersiveFullscreenRoute,
}

const ImmersiveRouteRouteWithChildren = ImmersiveRouteRoute._addFileChildren(
  ImmersiveRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ImmersiveRouteRoute: ImmersiveRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
