/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as ImmersiveRouteRouteImport } from './pages/_immersive/route'
import { Route as AuthRouteRouteImport } from './pages/_auth/route'
import { Route as AppRouteRouteImport } from './pages/_app/route'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AppAuthedRouteRouteImport } from './pages/_app/_authed/route'
import { Route as ImmersiveFullscreenIndexRouteImport } from './pages/_immersive/fullscreen/index'
import { Route as AuthLoginIndexRouteImport } from './pages/_auth/login/index'
import { Route as AppWorkIndexRouteImport } from './pages/_app/work/index'
import { Route as AppUnauthorizedIndexRouteImport } from './pages/_app/unauthorized/index'
import { Route as AppProcessIndexRouteImport } from './pages/_app/process/index'
import { Route as AppHomeIndexRouteImport } from './pages/_app/home/index'
import { Route as AppFeaturesIndexRouteImport } from './pages/_app/features/index'
import { Route as AppCustomRouteIndexRouteImport } from './pages/_app/custom-route/index'
import { Route as AppContactIndexRouteImport } from './pages/_app/contact/index'
import { Route as AppAboutIndexRouteImport } from './pages/_app/about/index'
import { Route as AppAuthedAdminRouteRouteImport } from './pages/_app/_authed/_admin/route'
import { Route as AppAuthedDashboardIndexRouteImport } from './pages/_app/_authed/dashboard/index'
import { Route as AppAuthedAdminAdminRouteRouteImport } from './pages/_app/_authed/_admin/admin/route'
import { Route as AppAuthedAdminAdminUsersIndexRouteImport } from './pages/_app/_authed/_admin/admin/users/index'

const ImmersiveRouteRoute = ImmersiveRouteRouteImport.update({
  id: '/_immersive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthedRouteRoute = AppAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRouteRoute,
} as any)
const ImmersiveFullscreenIndexRoute =
  ImmersiveFullscreenIndexRouteImport.update({
    id: '/fullscreen/',
    path: '/fullscreen/',
    getParentRoute: () => ImmersiveRouteRoute,
  } as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppWorkIndexRoute = AppWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUnauthorizedIndexRoute = AppUnauthorizedIndexRouteImport.update({
  id: '/unauthorized/',
  path: '/unauthorized/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProcessIndexRoute = AppProcessIndexRouteImport.update({
  id: '/process/',
  path: '/process/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHomeIndexRoute = AppHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFeaturesIndexRoute = AppFeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomRouteIndexRoute = AppCustomRouteIndexRouteImport.update({
  id: '/custom-route/',
  path: '/custom-route/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactIndexRoute = AppContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutIndexRoute = AppAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthedAdminRouteRoute = AppAuthedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedDashboardIndexRoute = AppAuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedAdminAdminRouteRoute =
  AppAuthedAdminAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AppAuthedAdminRouteRoute,
  } as any)
const AppAuthedAdminAdminUsersIndexRoute =
  AppAuthedAdminAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AppAuthedAdminAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about/': typeof AppAboutIndexRoute
  '/contact/': typeof AppContactIndexRoute
  '/custom-route/': typeof AppCustomRouteIndexRoute
  '/features/': typeof AppFeaturesIndexRoute
  '/home/': typeof AppHomeIndexRoute
  '/process/': typeof AppProcessIndexRoute
  '/unauthorized/': typeof AppUnauthorizedIndexRoute
  '/work/': typeof AppWorkIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/fullscreen/': typeof ImmersiveFullscreenIndexRoute
  '/admin': typeof AppAuthedAdminAdminRouteRouteWithChildren
  '/dashboard/': typeof AppAuthedDashboardIndexRoute
  '/admin/users/': typeof AppAuthedAdminAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutIndexRoute
  '/contact': typeof AppContactIndexRoute
  '/custom-route': typeof AppCustomRouteIndexRoute
  '/features': typeof AppFeaturesIndexRoute
  '/home': typeof AppHomeIndexRoute
  '/process': typeof AppProcessIndexRoute
  '/unauthorized': typeof AppUnauthorizedIndexRoute
  '/work': typeof AppWorkIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/fullscreen': typeof ImmersiveFullscreenIndexRoute
  '/admin': typeof AppAuthedAdminAdminRouteRouteWithChildren
  '/dashboard': typeof AppAuthedDashboardIndexRoute
  '/admin/users': typeof AppAuthedAdminAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_immersive': typeof ImmersiveRouteRouteWithChildren
  '/_app/_authed': typeof AppAuthedRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/_authed/_admin': typeof AppAuthedAdminRouteRouteWithChildren
  '/_app/about/': typeof AppAboutIndexRoute
  '/_app/contact/': typeof AppContactIndexRoute
  '/_app/custom-route/': typeof AppCustomRouteIndexRoute
  '/_app/features/': typeof AppFeaturesIndexRoute
  '/_app/home/': typeof AppHomeIndexRoute
  '/_app/process/': typeof AppProcessIndexRoute
  '/_app/unauthorized/': typeof AppUnauthorizedIndexRoute
  '/_app/work/': typeof AppWorkIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_immersive/fullscreen/': typeof ImmersiveFullscreenIndexRoute
  '/_app/_authed/_admin/admin': typeof AppAuthedAdminAdminRouteRouteWithChildren
  '/_app/_authed/dashboard/': typeof AppAuthedDashboardIndexRoute
  '/_app/_authed/_admin/admin/users/': typeof AppAuthedAdminAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/'
    | '/contact/'
    | '/custom-route/'
    | '/features/'
    | '/home/'
    | '/process/'
    | '/unauthorized/'
    | '/work/'
    | '/login/'
    | '/fullscreen/'
    | '/admin'
    | '/dashboard/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/custom-route'
    | '/features'
    | '/home'
    | '/process'
    | '/unauthorized'
    | '/work'
    | '/login'
    | '/fullscreen'
    | '/admin'
    | '/dashboard'
    | '/admin/users'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_immersive'
    | '/_app/_authed'
    | '/_app/'
    | '/_app/_authed/_admin'
    | '/_app/about/'
    | '/_app/contact/'
    | '/_app/custom-route/'
    | '/_app/features/'
    | '/_app/home/'
    | '/_app/process/'
    | '/_app/unauthorized/'
    | '/_app/work/'
    | '/_auth/login/'
    | '/_immersive/fullscreen/'
    | '/_app/_authed/_admin/admin'
    | '/_app/_authed/dashboard/'
    | '/_app/_authed/_admin/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ImmersiveRouteRoute: typeof ImmersiveRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_immersive': {
      id: '/_immersive'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ImmersiveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_authed': {
      id: '/_app/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_immersive/fullscreen/': {
      id: '/_immersive/fullscreen/'
      path: '/fullscreen'
      fullPath: '/fullscreen/'
      preLoaderRoute: typeof ImmersiveFullscreenIndexRouteImport
      parentRoute: typeof ImmersiveRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/work/': {
      id: '/_app/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof AppWorkIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/unauthorized/': {
      id: '/_app/unauthorized/'
      path: '/unauthorized'
      fullPath: '/unauthorized/'
      preLoaderRoute: typeof AppUnauthorizedIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/process/': {
      id: '/_app/process/'
      path: '/process'
      fullPath: '/process/'
      preLoaderRoute: typeof AppProcessIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/home/': {
      id: '/_app/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AppHomeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/features/': {
      id: '/_app/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof AppFeaturesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/custom-route/': {
      id: '/_app/custom-route/'
      path: '/custom-route'
      fullPath: '/custom-route/'
      preLoaderRoute: typeof AppCustomRouteIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contact/': {
      id: '/_app/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof AppContactIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/about/': {
      id: '/_app/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AppAboutIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_authed/_admin': {
      id: '/_app/_authed/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthedAdminRouteRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/_app/_authed/dashboard/': {
      id: '/_app/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppAuthedDashboardIndexRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/_app/_authed/_admin/admin': {
      id: '/_app/_authed/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAuthedAdminAdminRouteRouteImport
      parentRoute: typeof AppAuthedAdminRouteRoute
    }
    '/_app/_authed/_admin/admin/users/': {
      id: '/_app/_authed/_admin/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAuthedAdminAdminUsersIndexRouteImport
      parentRoute: typeof AppAuthedAdminAdminRouteRoute
    }
  }
}

interface AppAuthedAdminAdminRouteRouteChildren {
  AppAuthedAdminAdminUsersIndexRoute: typeof AppAuthedAdminAdminUsersIndexRoute
}

const AppAuthedAdminAdminRouteRouteChildren: AppAuthedAdminAdminRouteRouteChildren =
  {
    AppAuthedAdminAdminUsersIndexRoute: AppAuthedAdminAdminUsersIndexRoute,
  }

const AppAuthedAdminAdminRouteRouteWithChildren =
  AppAuthedAdminAdminRouteRoute._addFileChildren(
    AppAuthedAdminAdminRouteRouteChildren,
  )

interface AppAuthedAdminRouteRouteChildren {
  AppAuthedAdminAdminRouteRoute: typeof AppAuthedAdminAdminRouteRouteWithChildren
}

const AppAuthedAdminRouteRouteChildren: AppAuthedAdminRouteRouteChildren = {
  AppAuthedAdminAdminRouteRoute: AppAuthedAdminAdminRouteRouteWithChildren,
}

const AppAuthedAdminRouteRouteWithChildren =
  AppAuthedAdminRouteRoute._addFileChildren(AppAuthedAdminRouteRouteChildren)

interface AppAuthedRouteRouteChildren {
  AppAuthedAdminRouteRoute: typeof AppAuthedAdminRouteRouteWithChildren
  AppAuthedDashboardIndexRoute: typeof AppAuthedDashboardIndexRoute
}

const AppAuthedRouteRouteChildren: AppAuthedRouteRouteChildren = {
  AppAuthedAdminRouteRoute: AppAuthedAdminRouteRouteWithChildren,
  AppAuthedDashboardIndexRoute: AppAuthedDashboardIndexRoute,
}

const AppAuthedRouteRouteWithChildren = AppAuthedRouteRoute._addFileChildren(
  AppAuthedRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAuthedRouteRoute: typeof AppAuthedRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAboutIndexRoute: typeof AppAboutIndexRoute
  AppContactIndexRoute: typeof AppContactIndexRoute
  AppCustomRouteIndexRoute: typeof AppCustomRouteIndexRoute
  AppFeaturesIndexRoute: typeof AppFeaturesIndexRoute
  AppHomeIndexRoute: typeof AppHomeIndexRoute
  AppProcessIndexRoute: typeof AppProcessIndexRoute
  AppUnauthorizedIndexRoute: typeof AppUnauthorizedIndexRoute
  AppWorkIndexRoute: typeof AppWorkIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthedRouteRoute: AppAuthedRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAboutIndexRoute: AppAboutIndexRoute,
  AppContactIndexRoute: AppContactIndexRoute,
  AppCustomRouteIndexRoute: AppCustomRouteIndexRoute,
  AppFeaturesIndexRoute: AppFeaturesIndexRoute,
  AppHomeIndexRoute: AppHomeIndexRoute,
  AppProcessIndexRoute: AppProcessIndexRoute,
  AppUnauthorizedIndexRoute: AppUnauthorizedIndexRoute,
  AppWorkIndexRoute: AppWorkIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ImmersiveRouteRouteChildren {
  ImmersiveFullscreenIndexRoute: typeof ImmersiveFullscreenIndexRoute
}

const ImmersiveRouteRouteChildren: ImmersiveRouteRouteChildren = {
  ImmersiveFullscreenIndexRoute: ImmersiveFullscreenIndexRoute,
}

const ImmersiveRouteRouteWithChildren = ImmersiveRouteRoute._addFileChildren(
  ImmersiveRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ImmersiveRouteRoute: ImmersiveRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
